CREATE DATABASE RAILWAYTICKETBOOKAPPDB;
USE RAILWAYTICKETBOOKAPPDB;

CREATE TABLE REGISTER(
	NM VARCHAR(15),
    PHNO VARCHAR(10),
    EMAIL VARCHAR(50) UNIQUE,
    ADDRESS VARCHAR(100),
    AGE INT,
    UNAME VARCHAR(10) NOT NULL,
    PASS VARCHAR(10) NOT NULL,
    CONSTRAINT REGISTER_NM_PK PRIMARY KEY(NM)
);
SELECT * FROM REGISTER;
DESC REGISTER;


CREATE TABLE TRAIN (
	SERIAL_NO INT,
    TNUMBER VARCHAR(10) UNIQUE,
	TNAME VARCHAR(64) NOT NULL,
	START_STATION VARCHAR(32) NOT NULL,
	END_STATION VARCHAR(32) NOT NULL,
    CONSTRAINT TRAIN_TNUMBER_PK PRIMARY KEY(TNUMBER)
);
SELECT * FROM TRAIN;
DROP TABLE TRAIN;
DESC TRAIN;


CREATE TABLE STATIONS (
	TNUMBER VARCHAR(10) NOT NULL,
	SID INT,
	SNAME VARCHAR(30) NOT NULL,
    DI_F_S INT,
	ARRIVE_TIME TIME NOT NULL,
	DEPARTURE_TIME TIME NOT NULL,
	FOREIGN KEY (TNUMBER) REFERENCES TRAIN(TNUMBER)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

TRUNCATE TABLE STATIONS;
DESC STATIONS;
DROP TABLE STATIONS;


CREATE VIEW MAIN
AS
SELECT DISTINCT T.SERIAL_NO,T.TNUMBER,T.TNAME,T.START_STATION,T.END_STATION,S.SID,S.SNAME,S.DI_F_S,S.ARRIVE_TIME,S.DEPARTURE_TIME
FROM TRAIN T,STATIONS S
WHERE T.TNUMBER=S.TNUMBER;
DESC MAIN;
SELECT * FROM MAIN;
DROP VIEW MAIN;

SELECT DISTINCT t1.TNUMBER, t1.TNAME, t1.START_STATION, t1.END_STATION
FROM MAIN t1
JOIN MAIN t2 
  ON t1.TNUMBER = t2.TNUMBER   -- same train
WHERE t1.SNAME = 'Asansol'     -- user FROM station
  AND t2.SNAME = 'Durgapur'    -- user TO station
  AND t1.SID < t2.SID;         -- ensure travel direction


CREATE TABLE TICKETS (
   TICKET_ID INT PRIMARY KEY AUTO_INCREMENT,
   TRAIN_NO VARCHAR(10),
   TRAIN_NAME VARCHAR(100),
   FROM_STATION VARCHAR(100),
   TO_STATION VARCHAR(100),
   PASSENGER_NAME VARCHAR(100),
   AGE INT,
   GENDER VARCHAR(10),
   FARE DOUBLE,
   BOOKING_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE TICKETS ADD COLUMN USERNAME VARCHAR(10) NOT NULL UNIQUE;
TRUNCATE TABLE TICKETS;
DROP TABLE TICKETS;
SELECT * FROM TICKETS;

